version: 2
jobs:
  go1.16:
    docker:
      - image: circleci/golang:1.16-node
    working_directory: /go/src/github.com/fatedier/frp
    steps:
      - checkout
      - run: make
      - run: make alltest
  go1.15:
    docker:
      - image: circleci/golang:1.15-node
    working_directory: /go/src/github.com/fatedier/frp
    steps:
      - checkout
      - run: make
      - run: make alltest

workflows:
  version: 2
  build_and_test:
    jobs:
      - go1.16
      - go1.15
